sprint 1 / step 2
dqrest/ya-react-burger pull request #4
Opened 2023-04-07 12:22 UTC by dqrest

2023-04-08 06:03 UTC, andryxxa93 requested changes
Проделана большая работа 👍 

Что понравилось:
- Хороший `codestyle`
- Есть отписка от слушателя событий
- Реализован механизм закрытие модалки по `ESC` 

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- Добавьте проверку успешности запроса
- Уберите лишний `async`
- У некоторых компонентов не все пропсы указаны в `propTypes`
- у ModalOverlay не должно быть children, это просто компонент подложки а не контейнер. Так как это отдельный компоненты - вынесите его в отдельную директорию.
- Добавьте `isRequired` там где его не хватает

Более подробно описание проблемы смотрите комментарии в pull request.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-04-08 06:03 UTC, andryxxa93 commented on src/components/app/app.tsx
> +            .then(res => res.json())
**Надо исправить**
Добавьте проверку ответа сервера - res.ok:

Например:

```
.then(res => res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
```

иначе сейчас, если сервер ответи не кодом 2xx, а какой либо ошибкой (4xx, 5xx) мы не попадем в catch т.к. в этом случае fetch не выбрасывает ошибку, мы попытаемся отрисовать данные, хотя они не пришли, в итоге на попытке отрисовки несуществующих данных упадет все приложение

[https://learn.javascript.ru/fetch](https://learn.javascript.ru/fetch)

[https://developer.mozilla.org/en-US/docs/Web/API/Response/ok](https://developer.mozilla.org/en-US/docs/Web/API/Response/ok)

Т.к. эта проверка нужна у всех запросов, лучше вынести её в отдельную функцию

```
const checkReponse = (res) => {
  return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
};
```

`fetch(someUrl).then(checkReponse)`

2023-04-08 06:03 UTC, andryxxa93 commented on src/components/app/app.tsx
> +        fetch(dataUrl)
**Можно лучше**

в дальнейшем добавятся ещё запросы к бэкенду и лучше вынести описание этих запросов в функции

Например:

```
function getIngredients() {
   return fetch(`${NORMA_API}/ingredients`)
    .then(проверка ответа)
}

```

и разместить их в отдельном файле  `utils/burger-api.js`, а не описывать запросы в самом компоненте

2023-04-08 06:03 UTC, andryxxa93 commented on src/components/app/app.tsx
> +        const asyncGetBurgers = async () => getBurgers();
**Необходимо исправить**
Тут `async` не нужен так как вы не используете `await`.

2023-04-08 06:03 UTC, andryxxa93 commented on src/components/burger-ingredient-item/burger-ingredient-item.jsx
> +export default function BurgerIngredientItem({ count, burger, itemClick }) {
**Можно лучше**
Сложные операции желательно оборачивать в хук `useMemo` чтобы избежать ненужных выполнений. 
https://ru.reactjs.org/docs/hooks-reference.html#usememo

2023-04-08 06:03 UTC, andryxxa93 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +    let buns = burgers?.filter(b => b.type === "bun") || [];
**Можно лучше**

**здесь и далее в других местах** если переменная не перезаписывается её нужно объявлять как `const`, это помогает понять другим разработчикам, как мы будем использовать переменную, будем ли мы в коде перезаписывать её значение.
Так же стоит помнить, что добавление элемента в массив или изменение свойства объект не являются перезаписью самой переменной, а только изменяют его внутренне состояние и такие переменные так же объявляются как const

2023-04-08 06:03 UTC, andryxxa93 commented on src/components/modal/modal.jsx
> +const ModalOverlay = React.forwardRef(({ children, click }, ref) => {
**Надо исправить**

у ModalOverlay не должно быть children, это просто компонент подложки а не контейнер

2023-04-08 06:03 UTC, andryxxa93 commented on src/components/ingredient-details/ingredient-details.jsx
> +    burger: burgerIngredientsItemDto
**Надо исправить**

в описании propTypes этого и других компонентов нужно указывать .isRequired у пропсов, без этого не контролируется, что пропс передается

Проверьте во всем проекте

2023-04-09 05:18 UTC, dqrest commented on src/components/app/app.tsx
> +            .then(res => res.json())
Добавлен файл shared/utils/check-response.js c функцией checkResponse.
Импорт функции checkResponse в app.jsx.

2023-04-09 09:14 UTC, dqrest commented on src/components/app/app.tsx
> +        fetch(dataUrl)
Сделано.

2023-04-09 09:15 UTC, dqrest commented on src/components/app/app.tsx
> +        const asyncGetBurgers = async () => getBurgers();
Хорошо. Поправил.

2023-04-09 09:16 UTC, dqrest commented on src/components/modal/modal.jsx
> +const ModalOverlay = React.forwardRef(({ children, click }, ref) => {
Исправил. Создан отдельный компонент в components/model-overlay.js

2023-04-09 09:38 UTC, dqrest commented on src/components/ingredient-details/ingredient-details.jsx
> +    burger: burgerIngredientsItemDto
Добавлены PropTypes в компоненты:
- burger-ingredient-item
- ingredient-details
- modal
- modal-overlay

2023-04-09 09:53 UTC, dqrest commented on src/components/burger-ingredients/burger-ingredients.jsx
> +    let buns = burgers?.filter(b => b.type === "bun") || [];
Заменил let на const в следующих компонентах:
- burger-ingredients
- burger-constructor

2023-04-09 10:00 UTC, dqrest commented on src/components/burger-ingredient-item/burger-ingredient-item.jsx
> +export default function BurgerIngredientItem({ count, burger, itemClick }) {
В BurgerIngredients использован useMemo для фильтра данных buns, sauces, mains.

2023-04-09 10:34 UTC, dqrest commented
Все замечания исправлены

2023-04-10 05:44 UTC, andryxxa93 approved these changes
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-04-11 08:18 UTC, merged