Sprint 2 / step 2
dqrest/ya-react-burger pull request #8
Opened 2023-04-22 17:07 UTC by dqrest

2023-04-22 17:35 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Используете `useMemo`
- Хорошая организация хранилища
- Dnd работает хорошо

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- В проекте стоит debugger - его необходимо удалить

<img width="1222" alt="Снимок экрана 2023-04-22 в 20 26 50" src="https://user-images.githubusercontent.com/60173362/233798254-0323cf84-eff2-4e7e-b116-d2ed45eec3ee.png">

- если экшен не выполняет сайдэффектов, то не должна диспатчится функция и пропускатсья через thunk
- Вы используете синтаксис typescript в javascript файле

Более подробно описание проблемы смотрите комментарии в pull request.

**Можно лучше**
-  лучше хранить в отдельном поле выбранную булку и в отдельном поле массив с начинками бургера, это сильно облегчит работу со стором в следующем этапе
`const constructorInitialState = { bun: null, ingredients: []};`

- желательно очищать конструктор после успешного получения номера заказа с сервера в блоке then, чтобы пользователь мог следующий заказ сделать, не удаляя старые ингредиенты

- лучше не давать нажать на кнопку Оформить заказ, пока пользователь не добавил булку в заказ.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-04-22 17:35 UTC, andryxxa93 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +    const { ingredients, ingredientsRequest, ingredientsFailed } = useSelector(store => {
**Можно лучше**
Хорошая практика - передавать в useSelector не анонимную, а именованную функцию. Это позволит избежать лишних вызовов useSelector. 
https://www.youtube.com/watch?v=SVG-x-4BQic

2023-04-22 17:35 UTC, andryxxa93 commented on src/services/actions/burger-constructor-ingredients.js
> +    return function (dispatch) {
**Надо исправить**

не совсем верно организован диспатчи простых экшенов, не требующих сайд эффектов.

Если действие не требует запросов к серверу или каких то побочных эффектов, то нужно дисптчить просто объект экшена, а не функцию

Например, как сделано сейчас:

Описана функция

```
export const moveConstructorItem = (dragIndex, hoverIndex) => (dispatch) => {
	dispatch({
		type: MOVE_CONSTRUCTOR_ITEM,
		dragIndex,
		hoverIndex,
	});
};

dispatch(moveConstructorItem(dragIndex, hoverIndex)); //будет задиспатчена функция
```

Если присмотреться, то в коде есть два dispatch. Что при этом происходит:

мы диспатчик функцию => thunk перехватывает функцию => thunk выполняет функцию => функция сама диспатчит экшен => экшен попадает в редьюсер

В случае экшена не требующего сайдэффектов 2, 3 и 4 звено в цепочке лишние, т.к. не нужно пропускать простые экшены через thunk

Как должно быть:

```
//такая функция называется action creator - она принимает данные и возвращает объект (а не функцию)
export const moveConstructorItem = (dragIndex, hoverIndex) => ({
	type: MOVE_CONSTRUCTOR_ITEM,
	dragIndex,
	hoverIndex,
});

dispatch(moveConstructorItem(dragIndex, hoverIndex));
```

Но в этом случае будет задиспатчен объект
при этом не будет в цепочке обработки экшена лишних шагов, экшен не будет перехвачен thunk т.к. является объектом, а не функцией, а попадет сразу в редюсер

Нужно исправить это замечание для всех подобных мест в проекте, где при диспатче нужно просто передать экшен в редьюсер, а не выполнять сайдэффекты.

2023-04-22 17:35 UTC, andryxxa93 commented on src/utils/order-api.js
> +export function makeOrderRequest(idIngredients): Promise<any> {
**Необходимо исправить**
Вы используете синтаксис `typescript` в `javascript` файле

2023-04-23 03:34 UTC, dqrest commented on src/services/actions/burger-constructor-ingredients.js
> +    return function (dispatch) {
Все диспатчи функций переделаны на диспатчи объектов в простых действиях без запросов к серверу. Исправлено.

2023-04-23 03:39 UTC, dqrest commented on src/utils/order-api.js
> +export function makeOrderRequest(idIngredients): Promise<any> {
Исправлены файлы burger-api.js, order-api.js, в которых удалены Promise.

2023-04-23 09:20 UTC, dqrest commented on src/components/burger-ingredients/burger-ingredients.jsx
> +    const { ingredients, ingredientsRequest, ingredientsFailed } = useSelector(store => {
Исправлено. Именованные функции для useSelector применены в компонентах order-details, burger-constructor

2023-04-23 16:38 UTC, andryxxa93 approved these changes
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-05-01 12:50 UTC, merged