Sprint 3 / step 1
dqrest/ya-react-burger pull request #9
Opened 2023-05-12 19:49 UTC by dqrest

2023-05-12 20:39 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Показываете ошибку при запросе 
- Хорошая работа с куками
- Настроены все редиректы

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- На странице профиля не хватает инпута для пароля. Так же там верстка не соответствует макету, пожалуйста посмотрите как в фигме.
- У вас стоит дебагер в коде
- Авторизованному юзеру не должен  быть доступен роут `/forgot-password` и `/register`
- Роут `/reset-password` должен быть доступен только через `/forgot-password`
- Кнопки "Отмена" и "Сохранить" должны быть скрыты или задизейблены до тех пор, пока юзер не внесет изменения в форму.
- Обновление токена должно работать на всех запросах использующих `ассesToken`
- После обновления токена в случае получения ошибки необходимо повторять ранее неудавшийся запрос. Для проверки ответа можете создать функцию, которая принимает `url` и опции запроса (хедеры и.т.п). Эта функция должна сначала сделать запрос по адресу с опциями, если запрос падает с ошибкой  `jwt-expired`, то нужно обновить accessToken с помощью refreshToken. После обновления необходимо просто повторить ранее неудавшийся запрос, но используя уже свежий токен.

Более подробно описание проблемы смотрите комментарии в pull request.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-05-13 13:39 UTC, dqrest commented
Исправлены следующие замечания:
1) для авторизованного пользователя в компоненте ProtectedRouteElement настроено перенаправление маршрутов /forgot-password, /reset-password, /register на fallback путь или на домашнюю страницу.
2) Роут /reset-password был доступен для авторизованного пользователя, но для гостя он был защищен параметрами access, email (см. проверку их наличия в компоненте ProtectedRouteElement), устанавливаемыми при восстановлении пароля в маршруте /forgot-password. Сейчас эти маршруты закрыты для авторизованного пользователя, а для гостя доступ к /reset-password разрешен только с через /forgot-password.

2023-05-13 14:16 UTC, dqrest commented
Исправлены следующие замечания:
1. В профиль пользователя добавлено поле "Пароль".
2. В профиле пользователя кнопки "Сохранить", "Отмена" доступны после заполнения всех полей формы.

2023-05-13 15:55 UTC, dqrest commented
Исправлены следующие замечания:
1. Убрал все debugger.
2. В файл ../utils/auth-api.js добавлена функция fetchWithRefresh для обновления accessToken с помощью refreshToken.
3. Функция fetchWithRefresh  применена для запросов makeOrderRequest, patchUserRequest, getUserRequest.

2023-05-14 08:25 UTC, andryxxa93 commented
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-05-17 14:24 UTC, merged